### ISSUE TITLE
ENH: add concomitant_lasso_path() function

### ISSUE THREAD

**Issue by mathurinm** [EugeneNdiaye/smoothed_concomitant_lasso#2]
a pure python wrapper should be enough
Most of the code at https://github.com/mathurinm/celer/blob/master/celer/homotopy.py#L14

can be reused I think

**Comment by EugeneNdiaye** [comment]
Exist already: SC_path in smoothed_concomitant.py.

**Comment by mathurinm** [comment]
Ok, to make it obvious we could import it in the init
